import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Mainvisual from '../components/Mainvisual'
import Contact from '../components/Contact'



export default function Home() {


  return (
    <>
     <Head>
        <title>랜딩플랫폼 원시그널 &amp; PWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Mainvisual />

    </>
  )
}



