import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Contact from '../components/Contact'



export default function Home() {


  return (
    <>
     <Head>
        <title>랜딩플랫폼 원시그널 구현</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></Script>
      <Contact />
    </>
  )
}



